### PR TITLE
Add MSBuild targets

### LINKED ISSUE #12: Add MSBuild targets package
Create a package that contains MSBuild targets for transforming on build. It should work on both Mono and .NET Core.

### PR DESCRIPTION
**Pull request by mhutch**
Add MSBuild targets, and various related fixes. Fixes #12.

### CODE REVIEW

**Comment by jjmanton** [comment]
I noticed the output nuget package, Mono.TextTemplating.Build does not include a .props or .targets file. Should it?

**Comment by mhutch** [comment]
> I noticed the output nuget package, Mono.TextTemplating.Build does not include a .props or .targets file. Should it?

Yes, I hadn't tested the package yet, I've been doing all my development using the unit tests that test the targets in place 🙂

I took a look at fixing it this evening but couldn't convince `dotnet pack` to pack the project. It seems to think that a package has to have dependencies or libraries, and cannot just contain targets/tasks. I'll need to file a bug with NuGet and work around this using a nuspec.

**Comment by mhutch** [comment]
@jjmanton I fixed it and verified I can use the package from a project

**Comment by jjmanton** [comment]
Looking great! I just tried it out and the nuget package looks right to me. 

I had one minor issue. We have an interesting situation where we have net48 SDK style projects, that we are building on Mac/linux using reference assemblies. For some reason, the `Build` target isnt invoked in that scenario, so templates are never transformed. I had to manually add this to my csproj - 

```
  <Target Name="CallTemplateBuild" BeforeTargets="BeforeBuild">
    <CallTarget Targets="_TransformTemplates" />
  </Target>
```

I believe the problem is in this section of the .targets file, but I am not 100% sure - 

```
  <!-- this is invoked in full builds -->
  <Target Name="_TransformTemplatesOnBuild"
          BeforeTargets="Build"
          Condition="'$(TransformOnBuild)'=='True' Or '$(UseLegacyT4Preprocessing)' == 'False'"
          DependsOnTargets="_SetTransformOnBuildProperties;_TransformTemplates" />
```

Possibly `BeforeTargets` should be something like `BeforeTargets="BeforeBuild"` ? I am not an expert in this area, so please correct me if this would be an incorrect approach.

**Comment by mhutch** [comment]
@jjmanton That's odd. What properties are you setting and what item types are you using?

I attempted a minimal repo but did not see the problem you describe: https://gist.github.com/mhutch/b7a67bbcc6dd21cf092a80d031cb3393

If you take a look at the binary log (https://msbuildlog.com/) it will probably be easier to figure out why targets are not running.

**Comment by jjmanton** [comment]
I figured out my mistake. We use t4 to generate c# source files, and it was never actually hitting the "Build" target because "CoreCompile" failed. Apparently the "Build" target is invoked towards the end.

I noticed in the example you posted, the order of build is something like this (abbreviated) - 
- BeforeBuild
- PrepareForBuild
- CoreCompile
- AfterCompile
- AfterBuild
- _TransformTemplates
- Build

I am wondering if it is possible to have t4 templates transform before we hit CoreCompile so we can continue to use them to generate source files?

**Comment by mhutch** [comment]
@jjmanton should work now. i fixed the preprocessed template tests to check that the generated class actually ends up in the assembly.

**Comment by jjmanton** [comment]
@mhutch Yep, this is working great now! Nice work!

Cant wait to get this one merged and we can start using it.

**Comment by mhutch** [comment]
Yeah, I need to figure out what I need to get done before merging this. Off the top of my head:

Must-have:

- [ ] Get some more eyes on the MSBuild APIs (items/properties/metadata/targets) so I don't have to break them later
- [ ] Logging at normal/detailed/diagnostic levels
- [ ] Property to build templates in debug mode

Maybe before merging:

- [ ] Item metadata to override output file name
- [ ] Item metadata to override generated class name
- [ ] Item metadata to pass arguments to individual files
- [ ] Make some MSBuild properties available to the templates automatically, either on the generated base class or on a custom host

Definitely after merging:

- [ ] Build/execute templates out of process 
- [ ] Host Roslyn in the templating process
- [ ] Split into two phases (code generation before ResolveReferenceAssemblies, compilation/execution after ResolveReferences) so preprocessed templates can emit unresolved references and transformed templates can consume resolved references
- [ ] Implement some way to debug the templates

@jjmanton anything else you'd like to see?

**Comment by iskiselev** [comment]
Where will be transformed files written after msbuild task? In multi-targeting build _TransformTemplatesCore will be called once per TargetFramework, and if transform will have same destination for different TargetFramework (which I believe will be the case at least for UseLegacyT4Preprocessing), it may have race condition problem - when two transforms will try to open same output file concurrently.
I have similar issue when worked with some other preprocessing - see dotnet/msbuild#2781 for details.

**Comment by mhutch** [comment]
> Where will be transformed files written after msbuild task? In multi-targeting build _TransformTemplatesCore will be called once per TargetFramework, and if transform will have same destination for different TargetFramework (which I believe will be the case at least for UseLegacyT4Preprocessing), it may have race condition problem - when two transforms will try to open same output file concurrently.

I'll have to double-check target ordering, but what should happen in that case is that the transform is performed by the outer build. Assuming incremental build is enabled, the inner (per-framework) builds will see that the file is up to date.

**Comment by Blackclaws** [comment]
I tried testing this locally, however I have no idea how to actually use it properly. My expectation going in was that it would allow me to specify T4 files to preprocess into partial c# classes that I could then call from other code. 

I tried doing:
```
<T4Preprocess Include="**\*.tt" />
```

however that just resulted in a ArgumentNullException:
```
  Mono.TextTemplating.Build.targets(81, 5): [MSB4018] The "TextTransform" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Mono.TextTemplating.Build.TemplateBuildState.GetStaleAndNewTemplates(TemplateBuildState previousBuildState, Boolean preprocessOnly, Func`2 getFileWriteTime) in /_/Mono.TextTemplating.Build/TemplateBuildState.cs:line 80
   at Mono.TextTemplating.Build.TextTransformProcessor.Process(TaskLoggingHelper taskLog, TemplateBuildState previousBuildState, TemplateBuildState buildState, Boolean preprocessOnly) in /_/Mono.TextTemplating.Build/TextTransformProcessor.cs:line 22
   at Mono.TextTemplating.Build.TextTransform.Execute() in /_/Mono.TextTemplating.Build/TextTransform.cs:line 111
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

I want to use .tt files as part of a Source Generator project where those would be very helpful indeed. The current workaround is to just call t4 on build using an exec task, that has its own set of problems however. Any advice on how to correctly use these build targets would be great :)

**Comment by Blackclaws** [comment]
I found out what was causing my issue. A clean rebuild solved it but I think its relevant as its a bit of a bug anyway.

If you add a file first with
```
<T4Transform Include="foo.tt" />
```
and then change it to:
```
<T4Preprocess Include="foo.tt" />
```
without running a clean on the project it then runs into the error I got.

**Comment by Blackclaws** [comment]
I've been wondering. Is there a way to change the build targets in such a way that the compiled files show up as items that depend on the source template? That way you can take a look at the result right there in the editor.

Adding them as 
```
 <DependentUpon>TemplateFile </DependentUpon>
```
should probably do the trick. Though I'm not sure if that works with files in obj.

**Pull request merged**
