### PR TITLE
Trim trailing whitespace per editor config

### PR DESCRIPTION
**Pull request by atifaziz**
The `.editorconfig` says `trim_trailing_whitespace = true`:

https://github.com/mono/t4/blob/a80187de88cf5705aa454894b80c283b14212a6c/.editorconfig#L6-L10

This PR applies the rule to all files to avoid unrelated noise in future commits.

### CODE REVIEW

**Comment by mhutch** [comment]
Sorry, I'd rather not accept PRs that change formatting outside of other changes, as they make "git blame" less effective. However, PRs that change code for other reasons may fix its formatting.

**Comment by atifaziz** [comment]
> …as they make "git blame" less effective However, PRs that change code for other reasons may fix its formatting.

The argument flies both ways. Formatting and possible behavioural changes rolled into one make a commit nosier than it needs to be and harder to review. Moreover, since it's not atomic, you can't revert one logical change without the other. It makes `git revert` less effective. 😉 

That said, `git blame` has the [`-w`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt--w) (ignore whitespace) precisely for make it effective in spite of commits that simply make whitespace changes. You can also go one step further and use [`--ignore-rev`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt)/[`--ignore-revs-file`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt) for non-whitespace style changes to keep [`git blame`](https://git-scm.com/docs/git-blame) effective.

I am not going to fight for this PR to be merged (was meant as a quick favour for the project when I noticed the inconsistency) but I'd be more than happy to add a conventionally named `.git-blame-ignore-revs` file if that puts your concerns to rest. Let me know your final call.

**Comment by mhutch** [comment]
That's fair, I definitely appreciate your point but I'd like to err on the side of caution. It looks like GitHub doesn't currently support `.git-blame-ignore-revs`, might reconsider when it does.

**Comment by atifaziz** [comment]
> It looks like GitHub doesn't currently support `.git-blame-ignore-revs`, might reconsider when it does.

Commit history in GitHub doesn't follow renames/moves either à la `git log --follow`, which is a far bigger omission/issue. Does that mean one should never renames/moves files or reorg a project structure until GitHub is ready? I did say I am not going to fight this too hard so sorry for not resisting the temptation to present another side to your argument. You've made your call and I respect that.

**Comment by mhutch** [comment]
Thanks, I appreciate the input and will keep it in mind :)

**Pull request closed without merging**
