### PR TITLE
Fix race condition in temporary folder creation and clean it up on success

### PR DESCRIPTION
**Pull request by jgiannuzzi**
This PR fixes a race condition that can happen during the creation of the temporary folder for compilation. This can occur when processing many templates in parallel (whether in or out of process), especially on Windows where `Path.GetTempFileName` is not very random. The chosen fix is to create a temporary folder with a name based on the temporary file name and keep the file around as long as the folder exists.

This PR also cleans up the temporary folder once compilation is successful (unless template debugging is requested). In order to achieve that on Windows, the assembly needs to be loaded in memory with `Assembly.Load(byte[] rawAssembly)` instead of `Assembly.LoadFile(string path)`. The loading is now done in `TemplatingEngine.CompileCode`, where the temporary folder is created.

### CODE REVIEW

**Review by mhutch — APPROVED** [review]

**Comment by mhutch** [comment]
Thanks!

Batch usage is something I hadn't really though about much. I wonder whether we could use subdirectories in a single temp folder. Maybe we should also allow users to provide an explicit temp folder.

I momentarily balked at `Assembly.Load(byte[])` as it's less optimal than mmap'ing the assembly but I expect it's negligible compared to everything else that's being done. It also made me realize that we could rework things a bit such that when using the in-process compiler we can avoid writing the assembly to disk at all.

**Comment by jgiannuzzi** [comment]
Thanks for the merge, @mhutch!

Avoiding any disk writes when using the in-process compiler would be really neat indeed 👍

**Comment by iskiselev** [comment]
Are there any ideas when version with this fix will be released? I see builds failed due to file access race condition fixed here rather often in our CI. Thank you!

**Comment by mhutch** [comment]
Ah, I'm sorry, I wasn't aware anyone else was running into it frequently.

Unfortunately I noticed this regresses assembly unload so held off on making a release. I have a fix (https://github.com/mono/t4/commit/706d0ad345f5f084dcf2e39e41d8debe549e29db) in PR https://github.com/mono/t4/pull/110, which adds T4 MSBuild targets, and I'd been hoping to merge that (it's basically feature complete, just needs some review and polish) but I got distracted by other things.

I'll see whether I can backport the fix and make a release over the weekend.

While you're here, if the MSBuild targets are something you're interested in, I'd appreciate any feedback you have :)

**Comment by Bosch-Eli-Black** [comment]
We're running into this with our CI server, too.

@mhutch When you say that this regresses assembly unload, is that a critical bug, or do you think we'd be okay rolling our own hotfix release that just includes this PR?

Thanks 🙂

**Comment by mhutch** [comment]
Depends how you're using it. It's potentially an unbounded memory leak if you're hosting the engine in an long running process, but a non-issue if you're using `dotnet-t4` or similar.

While I was working in the `build-targets` branch I fell into the trap of doing a bunch of unrelated fixes and infrastructural work that was all intertwined/layered in a way that made it hard to separate out. I kept thinking it would be easier to finish and land that branch as a whole... but that wasn't the case.

I've now separated all that stuff out (including a fix for this issue) and landed it into main in https://github.com/mono/t4/pull/121, so I'll be able to get a release out soon.

In the meantime you can get preview packages here: https://github.com/orgs/mono/packages?repo_name=t4

**Comment by Bosch-Eli-Black** [comment]
@mhutch Okay, thanks! We're using `dotnet-t4`, so the memory leak shouldn't be an issue for us. Thanks for the tip about the preview packages; I'd forgotten that there were prebuilds available there 🙂

**Comment by iskiselev** [comment]
Sorry for bothering, but are there any chance to get at least preview release with this fix on public nuget? I'm mostly intersted in dotnet tool package.
It breaks our CI builds time-to-time.

**Pull request merged**
