### PR TITLE
RoslynCodeCompiler fix: Unused code which throws an exception has been removed

### PR DESCRIPTION
**Pull request by alexander-beck**

### CODE REVIEW

**Comment by mhutch** [comment]
What's the exception you're seeing? I'm not seeing one.

You're correct that `embeddedTexts` is unused. Looks like it needs to be passed to `Emit`.

**Comment by alexander-beck** [comment]
System.ArgumentException: 'Argument cannot be empty. Arg_ParamName_Name' 
 	
 is throw in 
 > Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.EmbeddedText.ValidateFilePath(string filePath) Line 205
 >Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.EmbeddedText.FromSource(string filePath, Microsoft.CodeAnalysis.Text.SourceText text) Line 102
> Mono.TextTemplating.Roslyn.dll!Mono.TextTemplating.RoslynCodeCompiler.CompileFileInternal.AnonymousMethod__3_2(Microsoft.CodeAnalysis.SyntaxTree st) Line 86

The FilePath of the CSharpSyntaxTree created in Mono.TextTemplating.Roslyn.dll!Mono.TextTemplating.RoslynCodeCompiler Line 70 is empty

**Comment by alexander-beck** [comment]
There was a better way to fix that issue than removing the line. 
The FilePath and the CanBeEmbedded-flag can to be set in the SourceText / SyntaxTree.
I am not sure how it should be passt to the Emit.

**Comment by mhutch** [comment]
I took another look at merging this, but found I'd already fixed it in 1b8b60ebebb9081497ae789334ce57f30d4640b2, which I have now backported from the `build-targets` branch to `main`. Thank for the contribution anyways :)

**Pull request closed without merging**
