### PR TITLE
[WIP] Add .NET Core 2.0 support

### PR DESCRIPTION
**Pull request by mhutch**

### CODE REVIEW

**Comment by mhutch** [comment]
@heaths I am the maintainer :)

However this is a side project and I haven't found much time to work on it lately.

**Comment by mhutch** [comment]
IIRC the build break appeared to be an issue with the CI machine rather than a real problem.

**Comment by heaths** [comment]
Duly noted (didn't initially notice the "owner" tag). :)

Seems the build machine's .NET Core SDK and the project might be out of sync, or maybe just a busted preview SDK. Says target _GetBuildOutputFilesWithTfm does not exist. Assuming it's a transient - or at least rectified issue - think you could rekick the builds and see if they pass? I'd be very interested in this and willing to help with any code changes for this in particular.

I've been trying to convert some .NET desktop projects over to dotnet for easier multi-targeting scenarios, but need to transform some files at build time to stamp the package version et. al. into arbitrary text files.

**Comment by mhutch** [comment]
Absolutely! There's already an issue: https://github.com/mono/t4/issues/12

**Pull request merged**
