### PR TITLE
GH42: Addressed constants not being defined

### LINKED ISSUE #42: PlatformNotSupportedException with dotnet-t4-project-tool
I have the global tool installed:

    T4 text template processor version 2.0.2+gbf09da0ad0

Using it, this command works:

    t4 -o tmp.cs -p:NAME=tmp -p:CONV=Cdecl -p:KIND=dynamic provider.tt

And I have a project dir with this in the csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.0.3" />
      </ItemGroup>
    </Project>

And after a dotnet restore to install the local tool, dotnet t4 yields:

     T4 text template processor version 2.0.3+gd133b088d6

But if I run the same command as above, except with "dotnet " prepended, I get:

    System.PlatformNotSupportedException: Operation is not supported on this platform.
       at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
       at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromDomBatch(CompilerParameters options, CodeCompileUnit[] ea)
       at Mono.TextTemplating.TemplatingEngine.CompileCode(IEnumerable`1 references, TemplateSettings settings, CodeCompileUnit ccu)
       at Mono.TextTemplating.TemplatingEngine.CompileTemplateInternal(ParsedTemplate pt, String content, ITextTemplatingEngineHost host)
       at Mono.TextTemplating.TemplatingEngine.CompileTemplate(ParsedTemplate pt, String content, ITextTemplatingEngineHost host)
       at Mono.TextTemplating.ToolTemplateGenerator.ProcessTemplate(ParsedTemplate pt, String inputFile, String inputContent, String& outputFile)
       at Mono.TextTemplating.TextTransform.MainInternal(String[] args)
       at Mono.TextTemplating.TextTransform.Main(String[] args)

dotnet --version says 2.1.500

The problem seems reproducible on Windows and Mac.

### PR DESCRIPTION
**Pull request by devlead**
@mhutch this fixes #42

Think there's need for some integration tests, essentially I know verified issues solved by in packages folder executing
```bash
dotnet tool install --tool-path=./tools --add-source=./ --version=2.1.0-preview-0024-gc005cbfae2 dotnet-t4
echo "<#@ parameter name='Name' #>Hello <#=Name#>" | tools/t4 -o - -p:Name=World
```
went 
```diff
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromDomBatch(CompilerParameters options, CodeCompileUnit[] ea)
   at Mono.TextTemplating.TemplatingEngine.CompileCode(IEnumerable`1 references, TemplateSettings settings, CodeCompileUnit ccu) in /Users/matkar/dev/gh/devlead/t4/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 271
   at Mono.TextTemplating.TemplatingEngine.CompileTemplateInternal(ParsedTemplate pt, String content, ITextTemplatingEngineHost host) in /Users/matkar/dev/gh/devlead/t4/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 175
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(ParsedTemplate pt, String content, ITextTemplatingEngineHost host) in /Users/matkar/dev/gh/devlead/t4/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 149
   at Mono.TextTemplating.ToolTemplateGenerator.ProcessTemplate(ParsedTemplate pt, String inputFile, String inputContent, String& outputFile) in /Users/matkar/dev/gh/devlead/t4/dotnet-t4/ToolTemplateGenerator.cs:line 59
   at Mono.TextTemplating.TextTransform.MainInternal(String[] args) in /Users/matkar/dev/gh/devlead/t4/dotnet-t4/TextTransform.cs:line 194
   at Mono.TextTemplating.TextTransform.Main(String[] args) in /Users/matkar/dev/gh/devlead/t4/dotnet-t4/TextTransform.cs:line 42
```
to
```
Hello World
```

I have some ideas around integration tests, if you're still at MVP Summit I would be have quick chat around those. Otherwise I could raise an issue if that's something you would think worth pursuing.

### CODE REVIEW

**Comment by devlead** [comment]
I it would seem `templateClassFullName` was left out in a previous merge for the 3.5 bits, so believe error unrelated to this PR, but want CI to complete so added in 3030373.

But there seems there might be an obsolete method used for for app domains ([CreateInstanceAndUnwrap](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.createinstanceandunwrap?view=netframework-3.5#System_AppDomain_CreateInstanceAndUnwrap_System_String_System_String_System_Boolean_System_Reflection_BindingFlags_System_Reflection_Binder_System_Object___System_Globalization_CultureInfo_System_Object___System_Security_Policy_Evidence_))

Not on Windows machine so will try to use the non obsoleted overload and see if CI compiles.

**Comment by devlead** [comment]
Ok change made Travis happy, AppVeyor is currently fighting a ddos so likely being triggered later, if not I'll do an rebase/force push later to see of it's triggered.

**Comment by devlead** [comment]
So while waiting for AppVeyor I setup an Azure Pipelines for my fork and it compiles [Build status](https://dev.azure.com/devleadse/Mono%20T4/_build/latest?definitionId=4). 
Needed a framework override to work with Azure Pipelines, which also triggered a AppVeyor. But I broke Travis. Will add an Windows conditional.

**Comment by devlead** [comment]
So now it compiles everywhere, let me know if you want me to do seperate focused PRs.

This is the yaml I used for Azure Pipelines
```yaml
resources:
- repo: self

jobs:

- job: Windows
  displayName: Build Windows VS2017
  pool:
    vmImage: Hosted VS2017
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.505 '
    inputs:
      version: '2.1.505 '

  - script: 'dotnet build Mono.TextTemplating.sln'
    displayName: '.NET Build'


- job: macOS
  displayName: Build macOS
  pool:
    vmImage: Hosted macOS
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.505 '
    inputs:
      version: '2.1.505 '

  - script: 'dotnet build Mono.TextTemplating.sln /P:FrameworkPathOverride="/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5"'
    displayName: '.NET Build'


- job: Ubuntu
  displayName: Build Ubuntu 1604
  pool:
    vmImage: Hosted Ubuntu 1604
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.505 '
    inputs:
      version: '2.1.505 '

  - script: 'dotnet build Mono.TextTemplating.sln /P:FrameworkPathOverride="/usr/lib/mono/4.5"'
    displayName: '.NET Build'
```

**Comment by mhutch** [comment]
Ah, this looks great, thanks for the fix!

I had to leave the MVP summit early but I'd love to hear your thoughts on integration tests.

**Pull request merged**
